DATA SEGMENT USE16
BLANKLINE DB 13, 10, '$'
MESG DB'Hello world!', '$'
MESG2 DB'sUUUUUUUH DUDE', '$'
MESG3 DB'sUUUUUUUH DUDE', '$'
DATA ENDS

CODE SEGMENT USE16
    ASSUME CS:CODE,DS:DATA
BEG:
    MOV AX,DATA
    MOV DS,AX
    MOV AH,9
    MOV DX, OFFSET MESG
    INT 21H
    MOV AH,9
    MOV DX, OFFSET BLANKLINE
    INT 21H
    MOV AH,9
    MOV DX, OFFSET MESG2
    INT 21H
    MOV AH,9
    MOV DX, OFFSET BLANKLINE
    INT 21H
    MOV AH,9
    MOV DX, OFFSET MESG3
    INT 21H
    MOV AH,4CH
    INT 21H
CODE ENDS
END BEG